#!/bin/bash
set -e

PHP_ERROR_REPORTING=${PHP_ERROR_REPORTING:-"E_ALL & ~E_DEPRECATED & ~E_NOTICE"}
PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-"512M"}

sed -ri 's/^display_errors\s*=\s*Off/display_errors = On/g' /etc/php5/apache2/php.ini
sed -ri 's/^display_errors\s*=\s*Off/display_errors = On/g' /etc/php5/cli/php.ini
sed -ri "s/^error_reporting\s*=.*$//g" /etc/php5/apache2/php.ini
sed -ri "s/^error_reporting\s*=.*$//g" /etc/php5/cli/php.ini
sed -ri "s/^memory_limit\s*=.*$//g" /etc/php5/apache2/php.ini
sed -ri "s/^memory_limit\s*=.*$//g" /etc/php5/cli/php.ini

echo "error_reporting = $PHP_ERROR_REPORTING" >> /etc/php5/apache2/php.ini
echo "error_reporting = $PHP_ERROR_REPORTING" >> /etc/php5/cli/php.ini
echo "memory_limit = $PHP_MEMORY_LIMIT" >> /etc/php5/apache2/php.ini
echo "memory_limit = $PHP_MEMORY_LIMIT" >> /etc/php5/cli/php.ini

source /etc/apache2/envvars && exec /usr/sbin/apache2 -DFOREGROUND
